### ISSUE TITLE
Javascript error when saving user preferences

### ISSUE THREAD

**Issue by fbarnard** [gocd/gocd#3576]
##### Issue Type
Bug Report
##### Summary

Javascript error when saving user preferences

##### Environment

Google Chrome v58.0.3029.110

```plain
Uncaught TypeError: t.validate is not a function
    at u (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at Object.beforeSend (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at Function.ajax (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at Object.<anonymous> (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at Function.Deferred (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at i.update (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:24)
    at HTMLFormElement.onsubmit (preferences-10188d28e223d3a66712.js:1)
    at HTMLFormElement.N.r (vendor-and-helpers.chunk-08f3e8e5c56b0f44c90a.js:1)
```
-->

**Comment by marques-work** [comment]
@arvindsv this was introduced with 93050fa23f56d8f37398e042421932c36529740d

**Comment by arvindsv** [comment]
Reopening - will wait for this to go through and verify.

**Comment by arvindsv** [comment]
Verified on: 17.6.0 (5142-be1ff52e07d80323fcc615864a64f3afe83b7016)
