### ISSUE TITLE
Go Server and Go Agent not working on macOS High Sierra

### ISSUE THREAD

**Issue by Mark-McCracken** [gocd/gocd#3934]
- Bug Report

##### Summary
Go Server and Go Agent both crash immediately on startup. Support team has said this is due to deprecated APIs in macOS High Sierra for accessing menu items in an application.

##### Environment
macOS 10.13 (17A405)
Tried java 8 and java 9, neither worked, as that's not the issue.

* Go Version: 
tried versions 17.10.0, 17.9.0,17.8.0
* JAVA Version: 
tried 9 (build 9+181) x86_64 and java 8 update 144 build 1.8.0_144-b01
* OS:
macOS 10.13 (17A405)
* Browser vendor and version (if relevant):
not relevant

##### Steps to Reproduce

1.  Install macOS 10.13
2. Download zip file from [here](https://www.gocd.org/download/#osx)
3. Unzip
4. Move app into applications
5. Open app.

##### Expected Results
application should start

##### Actual Results
does not start

##### Possible Fix
review deprecated APIs between macOS 10.12 and 10.13 and resolve code using those.

##### Log snippets

osx-app.log (server)
```

Tue Oct 10 11:08:19 BST 2017: Running:
Tue Oct 10 11:08:19 BST 2017:   /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
Tue Oct 10 11:08:19 BST 2017:   -cp
Tue Oct 10 11:08:19 BST 2017:   /Applications/Go Server.app/Contents/Resources/go.jar
Tue Oct 10 11:08:19 BST 2017:   -Xdock:icon=/Applications/Go Server.app/Contents/Resources/go-server.icns
Tue Oct 10 11:08:19 BST 2017:   -Xdock:name=Go Server
Tue Oct 10 11:08:19 BST 2017:   -Dgo.application.name=Go Server
Tue Oct 10 11:08:19 BST 2017:   -Dgo.java.to.use=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
Tue Oct 10 11:08:19 BST 2017:   -Dcruise.server.maxpermgen=256
Tue Oct 10 11:08:19 BST 2017:   -Dcruise.server.mem=512
Tue Oct 10 11:08:19 BST 2017:   -Dcruise.server.country=US
Tue Oct 10 11:08:19 BST 2017:   -Dgo.server.mac.go.jar.dir=/Applications/Go Server.app/Contents/Resources
Tue Oct 10 11:08:19 BST 2017:   -Dcom.apple.mrj.application.apple.menu.about.name=Go Server
Tue Oct 10 11:08:19 BST 2017:   -Dcruise.server.maxmem=1024
Tue Oct 10 11:08:19 BST 2017:   -Dapple.laf.useScreenMenuBar=true
Tue Oct 10 11:08:19 BST 2017:   -Dcruise.server.lang=en
Tue Oct 10 11:08:19 BST 2017:   com.thoughtworks.go.server.launcher.GoMacLauncher

Exception in thread "main" java.lang.NoSuchMethodError: com.apple.eawt.Application.addApplicationListener(Lcom/apple/eawt/ApplicationListener;)V
	at com.thoughtworks.go.server.launcher.GoMacLauncher.<init>(GoMacLauncher.java:54)
	at com.thoughtworks.go.server.launcher.GoMacLauncher.main(GoMacLauncher.java:50)

```

osx-app.log (agent)
``` 
Tue Oct 10 11:08:27 BST 2017: Setting working directory: /Users/mark.mccracken/Library/Application Support/Go Agent

Tue Oct 10 11:08:27 BST 2017: Setting environment variables:
AGENT_STARTUP_ARGS="-Xms128m -Xmx256m"

Tue Oct 10 11:08:27 BST 2017: Final environment variables are:
AGENT_STARTUP_ARGS=-Xms128m -Xmx256m
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OTEWktTB6k/Render
HOME=/Users/mark.mccracken
LOGNAME=mark.mccracken
OLDPWD=/
PATH=/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/mark.mccracken/Library/Application Support/Go Agent
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.CHIJ9LUnGP/Listeners
TMPDIR=/var/folders/3q/hb0y0z5556500zzlw4xf9228fy1c3r/T/
USER=mark.mccracken
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1DE0B078:0x0:0x2

Tue Oct 10 11:08:27 BST 2017: Running:
Tue Oct 10 11:08:27 BST 2017:   /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
Tue Oct 10 11:08:27 BST 2017:   -cp
Tue Oct 10 11:08:27 BST 2017:   /Applications/Go Agent.app/Contents/Resources/agent-bootstrapper.jar
Tue Oct 10 11:08:27 BST 2017:   -Xdock:icon=/Applications/Go Agent.app/Contents/Resources/go-agent.icns
Tue Oct 10 11:08:27 BST 2017:   -Xdock:name=Go Agent
Tue Oct 10 11:08:27 BST 2017:   -Dgo.application.name=Go Agent
Tue Oct 10 11:08:27 BST 2017:   -Dgo.java.to.use=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
Tue Oct 10 11:08:27 BST 2017:   -Dcruise.server.port=8153
Tue Oct 10 11:08:27 BST 2017:   -Djar-class-loader.main.class=com.thoughtworks.go.agent.bootstrapper.osx.AgentMacWindow
Tue Oct 10 11:08:27 BST 2017:   -Dcom.apple.mrj.application.apple.menu.about.name=Go Agent
Tue Oct 10 11:08:27 BST 2017:   -Dapple.laf.useScreenMenuBar=true
Tue Oct 10 11:08:27 BST 2017:   -Dcruise.server.host=127.0.0.1
Tue Oct 10 11:08:27 BST 2017:   com.thoughtworks.gocd.Boot
Tue Oct 10 11:08:27 BST 2017:   127.0.0.1 8153

Could not find file `config/agent-bootstrapper-log4j.properties'. Attempting to load from classpath.
Using classpath resource `config/agent-bootstrapper-log4j.properties'.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.thoughtworks.gocd.Boot.run(Boot.java:58)
	at com.thoughtworks.gocd.Boot.main(Boot.java:42)
Caused by: java.lang.NoSuchMethodError: com.apple.eawt.Application.setEnabledPreferencesMenu(Z)V
	at com.thoughtworks.go.agent.bootstrapper.osx.AgentMacWindow.initializeApplicationAdapter(AgentMacWindow.java:87)
	at com.thoughtworks.go.agent.bootstrapper.osx.AgentMacWindow.<init>(AgentMacWindow.java:66)
	at com.thoughtworks.go.agent.bootstrapper.osx.AgentMacWindow.main(AgentMacWindow.java:48)
	... 6 more
```

**Comment by bdpiparva** [comment]
@Mark-McCracken --- I have tried running `GoCD Server 17.10.0` and `GoCD Agent 17.10.0` with `jdk-8` and both are working fine in `macOS High Sierra version 10.13 (17A405)`. 

JDK-9 is not supported by GoCD yet and it is giving the same error that you have mentioned in logs.

**Comment by arvindsv** [comment]
Closing this since it is verified to work on High Sierra.

**Comment by kungfuslippers** [comment]
@arvindsv  Tried clean install of JDK-8 which didn't install for me on High Sierra. Therefore can't install Go CD. What is the timeframe for JDK-9 support?

@Mark-McCracken - Did you find a workaround for this?

**Comment by arvindsv** [comment]
In case someone comes across this: You need JDK 8, not JRE 8. Installing the JRE just installs the browser plugin in `/Library/Internet Plug-Ins`.

**Comment by Uko** [comment]
How can I specify the version of Java? When I run `/usr/libexec/java_home -V` I get

```
Matching Java Virtual Machines (2):
    9.0.1, x86_64:	"Java SE 9.0.1"	/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
    1.8.0_152, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
```

so to my knowledge, I have Java 8. But Go Server still starts with Java 9…

**Comment by Uko** [comment]
Yeah, it worked when I uninstalled java 9. But as long as it is available in the system, the Go apps will try to start with java 9. Isn't there a way to explicitly specify that java 8 has to be used? I remember doing a similar thing for Minecraft

**Comment by bdpiparva** [comment]
Use `launchctl ` to  set  `GO_JAVA_HOME` environment variable.

1. set env GO_JAVA_HOME
```bash
launchctl setenv GO_JAVA_HOME /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java
``` 
2. Launch the Go Server from GUI.
3. Check the java version used by GoCD server  -
```bash
$ cat osx-app.log | grep java.to.use                                                                                                                                                                                                 
Tue Jan 16 10:29:15 IST 2018:   -Dgo.java.to.use=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java
```

Above solution works for GoCD server and Agent both.

**Comment by ketan** [comment]
Reopening, it appears that GoCD is using deprecated APIs (with java 8). These have been removed starting java 9 (with some alternative apis).

See https://stackoverflow.com/questions/9239287/what-is-the-alternative-for-deprecated-com-apple-eawt-applicationlistener

**Comment by adityasood** [comment]
verified on  18.12.0-8160
